# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jetson-examples',
                'doc_host': 'https://ninjalabo.github.io',
                'git_url': 'https://github.com/ninjalabo/jetson-examples',
                'lib_path': 'jetson_examples'},
  'syms': {}}
